export const PARA_DATA = [
  {
    strong: "Testnet Upgrade: RISC Zero & Boundless Integration",
    para: "We successfully integrated RISC Zero zkVM and Boundless into the LayerEdge Testnet, enhancing trust-minimized verification with zero-knowledge proof-based execution. This integration enables efficient, verifiable off-chain computations while ensuring proofs remain lightweight and decentralized.",
  },

  {
    strong: "Massive Growth in Browser-Based Light Nodes",
    para: "Millions of users interacted with our browser-based light node infrastructure. We optimized performance to support scalable, trust-minimized verification at an unprecedented scale.",
  },

  {
    strong: "Community Proof Posting via LayerEdge Dashboard",
    para: "We enabled proof submission for the community, making decentralized verification accessible to all. Users can now post and interact with aggregated proofs directly on Bitcoin via the LayerEdge Dashboard — marking a major step toward a permissionless and inclusive proof validation ecosystem.",
  },

  {
    strong: "RISC Zero & Boundless",
    para: "We are leveraging RISC Zero’s zkVM and Boundless, bringing scalable and trust-minimized proof aggregation to the Bitcoin-backed internet.",
  },

  {
    strong: "Nexus Partnership",
    para: "We announced a collaboration with Nexus to explore proof aggregation solutions and drive shared ecosystem growth through technological innovation, joint go-to-market strategies, and community engagement.",
  },

  {
    strong: "OKX Integration",
    para: "We integrated with OKX Wallet for scalable zk verification, further advancing the vision of a Bitcoin-backed internet.",
  },
];
